version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: go-non-go-matrix-container
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # Declare which aws services will be used in localstack
      - SERVICES=dynamodb
      - DEBUG=1
      # These variables are needed for localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=devuser
      - AWS_SECRET_ACCESS_KEY=devaccesskey
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"