name: pre_commit

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Start docker compose
        run: sh ./localstack/init.sh

      - name: Run Tests
        run: npm run test

      - name: Stop docker compose
        run: docker-compose down

  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Run API Doc Generation
        run: npm run doc:generate